clients:
  - name: SecuredMe Education Gateway Dev
    app_type: regular_web
    is_first_party: true
    oidc_conformant: true
    callbacks:
      - https://gateway-dev.securedme.ca/auth/callback
    allowed_logout_urls:
      - https://gateway-dev.securedme.ca/
    allowed_origins:
      - https://algoquest-dev.securedme.ca
      - https://synthia-dev.securedme.ca
    web_origins:
      - https://algoquest-dev.securedme.ca
      - https://synthia-dev.securedme.ca
    grant_types:
      - authorization_code
    token_endpoint_auth_method: client_secret_post
    jwt_configuration:
      alg: RS256
      lifetime_in_seconds: 28800

resourceServers:
  - name: SecuredMe Education Gateway API Dev
    identifier: https://gateway.securedme.ca/api
    signing_alg: RS256
    allow_offline_access: false
    skip_consent_for_verifiable_first_party_clients: true
    token_lifetime: 3600
    token_lifetime_for_web: 3600

organizations:
  - name: securedme-synthetic-school
    display_name: SecuredMe Synthetic School
    metadata:
      environment: Development
      data_classification: synthetic-only
